# Generated by Django 3.2.6 on 2021-08-21 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_biometrico', models.IntegerField()),
                ('dui', models.CharField(max_length=10)),
                ('nit', models.CharField(max_length=17)),
                ('nup', models.CharField(max_length=10)),
                ('isss', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('escuela', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contratacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TiemposAccesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('salidad', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.IntegerField(default='1')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contratacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tipocontratacion'),
        ),
    ]
