# Generated by Django 3.2.6 on 2021-09-06 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreDoc', models.CharField(max_length=50)),
                ('DireccionDoc', models.CharField(max_length=50)),
                ('TelefonoDoc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEnfermedad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMedicamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePaciente', models.CharField(max_length=50)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.doctor')),
                ('Enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.enfermedad')),
                ('Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.medicamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo_contratacion',
        ),
        migrations.RemoveField(
            model_name='tiemposaccesso',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='TiemposAccesso',
        ),
        migrations.DeleteModel(
            name='TipoContratacion',
        ),
    ]
