# Generated by Django 3.2.6 on 2021-09-29 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20210905_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreComercio', models.CharField(max_length=50)),
                ('Patente', models.CharField(max_length=50)),
                ('Propietario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreDepartamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMunicipo', models.CharField(max_length=50)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DesQueja', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('Comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreRegion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreSucursal', models.CharField(max_length=50)),
                ('Comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.comercio')),
                ('Municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.municipio')),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Enfermedad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Enfermedad',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.AddField(
            model_name='queja',
            name='Sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.sucursal'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.region'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='Municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.municipio'),
        ),
    ]
